project:
  type: website

title: "Qilin Zhang's Website"
author: "Qilin Zhang"

website:
  favicon: "images/favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: project.qmd
        text: "Project"
      - href: cv.qmd
        text: "CV"
      - href: contact.qmd
        text: "Contact"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true





