---
title: "About Me"
---

# About Me

Welcome to my personal website!

**Professional Introduction:**  
I'm Qilin Zhang. I have 4+ years of experience in business analytics in both my undergraduate and graduate studies and specialize in working with data through Excel, R studio and Python, especially in the business marketplace and beyond. In my undergraduate studies, I learned more business-friendly knowledge, and in my graduate studies, I learned R Studio and Python in a systematic way to better fit the current era of analyzing and processing data in the big data era.

# Experience

- **University of California-Riverside**

  Bachelor’s in Business Administration  
  Relevant Courses: Decision Analysis, Management Science, Introduction to Computing, Statistics, and Organizational Behavior.
  
- **Boston University**  

  Master’s in Applied Business Analytics (in progress)  
  Relevant Courses: Marketing Analytics, Data Mining, Quantitative & Qualitative Decision-Making, and Web Analytics.
